# Generated by Django 2.2 on 2020-10-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_householdappliance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComputersLaptopsAndSoftware',
            new_name='Products',
        ),
        migrations.DeleteModel(
            name='HouseholdAppliance',
        ),
    ]
