# Generated by Django 2.2 on 2020-10-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201019_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategories',
            options={'verbose_name': 'Направление подготовки', 'verbose_name_plural': 'Направления подготовки'},
        ),
    ]
